apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 55-sssd-worker-ldap
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
    config:
      ignition:
        version: 3.1.0
      storage:
        files:
          - path: "/etc/sssd/pki/ldap_ca.crt"
            overwrite: true
            mode: 420
            user:
              id: 0
            group:
              id: 0
            contents:
              source: 
                data:text/plain;charset=utf-8;base64,<ldap_ca.crt.base64>
          - path: "/etc/sssd/sssd.conf"
            overwrite: true
            mode: 384
            user:
              id: 0
            group:
              id: 0
            contents:
              source: >-
                data:text/plain;charset=utf-8;base64,<sssd.conf.base64>
          # nsswitch.conf is optional, and only required if you are using sudo rules from ldap
          #- path: /etc/nsswitch.conf
          #  overwrite: true
          #  contents:
          #    source: >-
          #      data:text/plain;charset=utf-8;base64,<nsswitch.conf.base64>
          - path: /etc/pam.d/system-auth
            overwrite: true
            mode: 420
            contents:
              source: >-
                data:text/plain;charset=utf-8;base64,<system-auth.base64>
          # sshd_config is optional, and only required if you are using ssh public keys from ldap
          - path: /etc/ssh/sshd_config
            overwrite: true
            mode: 384
            user:
              id: 0
            group:
              id: 0
            contents:
              source: >-
                data:text/plain;charset=utf-8;base64,<sshd_config.base64>
